smiles: O
output_dir: .
device_type: cuda
method: MMMD
optimiser: adam
test_data_path: null
n_epochs: 1000
learning_rate: 0.0005
learning_rate_decay: 1.0
learning_rate_decay_step: 10
loss_force_weight: 0.1
initial_force_field: openff-2.2.1.offxml
ml_potential: ani2x
n_train_snapshots: 1000
n_test_snapshots: 1000
n_conformers: 10
n_iterations: 10
snapshot_interval: 10
n_equilibration_steps: 100
temperature: 500
timestep: 1.0
energy_lower_cutoff: 1.0
energy_upper_cutoff: 10.0
cluster_tolerance: 0.075
cluster_parallel: 1
data: null
memory: false
linear_harmonics: true
linear_torsions: false
use_modified_seminaro: false
modified_seminario_finite_step: 0.005291772
modified_seminario_tolerance: 0.0001
modified_seminario_vib_scaling: 0.957
