package:
  name: bespokefit2
  version: 1.0
  summary: Generate a Force-Field Parameterization from Single-Molecule MD

source:
  git_url: https://github.com/thomasjamespope/Bespokefit2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - smee
    - jupyter 
    - nglview 
    - smirnoff-plugins >=0.0.4
    - openmm 
    - openff-toolkit 
    - openff-units 
    - openff-interchange 
    - openmm-ml 
    - tensorboardX 
    - tensorboard

test:
  imports:
    -

about:
  home:
  license: MIT

