name: CI

on:
  push:
    branches:
      - "devel"
  pull_request:
    branches:
      - "devel"
  schedule:
    # Weekly tests run by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on ubuntu-latest, Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    container: condaforge/mambaforge:latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install package
        run: |
          apt update && apt install -y git make
          export BESPOKEFIT_SMEE_PYTHON_VERSION=${{ matrix.python-version }}
          export BESPOKEFIT_SMEE_CPU_INSTALL=1
          make env

      - name: Lint
        run: |
          make lint

      - name: Type check
        run: |
          make type-check

      - name: Run tests
        run: |
          make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
